// all widgets are included
#include "./angle_panel/angle_panel.h"
#include "./azimuth_panel/azimuth_panel.h"
#include "./bar/bar.h"
#include "./battery/battery.h"
#include "./editable_label/editable_label.h"
#include "./info_label/info_label.h"
#include "./panel/panel.h"
#include "./switcher_dual/switcher_dual.h"
#include "./title_bar/title_bar.h"
